-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.colour_star
(
    columnid integer NOT NULL,
    colour character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT colour_star_pkey PRIMARY KEY (columnid)
);

CREATE TABLE IF NOT EXISTS public.date
(
    dateid integer NOT NULL,
    date date NOT NULL,
    CONSTRAINT date_pkey PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public.parametrs
(
    starsid integer NOT NULL,
    constellation character varying COLLATE pg_catalog."default",
    CONSTRAINT parametrs_pkey PRIMARY KEY (starsid)
);

CREATE TABLE IF NOT EXISTS public.starparametrs
(
    productid integer NOT NULL,
    temperature numeric,
    mass numeric,
    "brightness " numeric,
    CONSTRAINT starparametrs_pkey PRIMARY KEY (productid)
);

CREATE TABLE IF NOT EXISTS public.stars
(
    categoryid integer NOT NULL,
    starnames character varying COLLATE pg_catalog."default",
    CONSTRAINT stars_pkey PRIMARY KEY (categoryid)
);

ALTER TABLE IF EXISTS public.colour_star
    ADD CONSTRAINT fkcolourstar FOREIGN KEY (columnid)
    REFERENCES public.stars (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS colour_star_pkey
    ON public.colour_star(columnid);


ALTER TABLE IF EXISTS public.date
    ADD CONSTRAINT consstarsfk FOREIGN KEY (dateid)
    REFERENCES public.parametrs (starsid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS date_pkey
    ON public.date(dateid);


ALTER TABLE IF EXISTS public.parametrs
    ADD CONSTRAINT parametrsfkstars FOREIGN KEY (starsid)
    REFERENCES public.stars (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS parametrs_pkey
    ON public.parametrs(starsid);


ALTER TABLE IF EXISTS public.starparametrs
    ADD CONSTRAINT starsparametr FOREIGN KEY (productid)
    REFERENCES public.stars (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS starparametrs_pkey
    ON public.starparametrs(productid);

END;